name: CCID_build
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print system info
        run: |
          uname -a
          sw_vers

      - name: Install dependencies
        run: |
          brew update
          brew install autoconf autoconf-archive automake m4  libtool make pkg-config pcsc-lite libusb
          ./bootstrap

      - name: configure
        run: |
          rm -f /opt/homebrew/Cellar/libusb/1.0.29/lib/libusb-1*.dylib
          rm -f /opt/homebrew/Cellar/libusb/1.0.29/lib/libusb-1.0.a
          cp libusb-1.0.a /opt/homebrew/Cellar/libusb/1.0.29/lib/
          export BUNDLE_ID=lm
          ./MacOSX/configure

      - name: make
        run: |
              make
              mkdir -p ifd-ccid-lm.bundle/Contents/MacOS/
              cp ./src/Info.plist ifd-ccid-lm.bundle/Contents/
              cp ./src/.libs/libccid.dylib ifd-ccid-lm.bundle/Contents/MacOS/
              lipo -info ifd-ccid-lm.bundle/Contents/MacOS/libccid.dylib
              #tar -czf ifd-ccid-lm.bundle.tar.gz ifd-ccid-lm.bundle
              
      - name: Upload final bundle
        uses: actions/upload-artifact@v4
        with:
          name: ifd-ccid-lm.bundle
          path: ifd-ccid-lm.bundle
          retention-days: 365
